In [4]:

function generate_reflections(hmax,nth)
    sc  = Dict{Int, Vector{Tuple{Int,Int,Int}}}()
    bcc = Dict{Int, Vector{Tuple{Int,Int,Int}}}()
    fcc = Dict{Int, Vector{Tuple{Int,Int,Int}}}()

    for h in 0:hmax, k in 0:hmax, l in 0:hmax

        N = h^2 + k^2 + l^2
        hkl = (h,k,l)

        # --- SC: alle erlaubten Reflexe ---
        if length(sc) == nth
            if N < maximum(keys(sc))
                delete!(sc, maximum(keys(sc)))
            end
        end 

        if length(fcc) == nth
            if N < maximum(keys(fcc))
                delete!(fcc, maximum(keys(fcc)))
            end
        end 

        if length(bcc) == nth
            if N < maximum(keys(bcc))
                delete!(bcc, maximum(keys(bcc)))
            end
        end 


        if length(sc) < nth
            push!(get!(sc, N, Vector{Tuple{Int,Int,Int}}()), hkl)
        end

        # --- BCC: h+k+l gerade ---
        if length(bcc) < nth
            if (h + k + l) % 2 == 0
                push!(get!(bcc, N, Vector{Tuple{Int,Int,Int}}()), hkl) 
            end
        end

        # --- FCC: alle h,k,l entweder alle gerade oder alle ungerade ---
        if length(fcc) < nth
            if (h % 2 == k % 2 == l % 2)
                push!(get!(fcc, N, Vector{Tuple{Int,Int,Int}}()), hkl)
            end
        end
    end
    sc_sorted = [(N, sc[N]) for N in sort(collect(keys(sc)))]
    bcc_sorted = [(N, bcc[N]) for N in sort(collect(keys(bcc)))]
    fcc_sorted = [(N, fcc[N]) for N in sort(collect(keys(fcc)))]
    return sc_sorted, bcc_sorted, fcc_sorted
end


generate_reflections (generic function with 1 method)

In [ ]:
function anglestheo(n)
    rfl=generate_reflections(n*log(n),n)[3]
    println(rfl)
    α = zeros(n)
    for i in 1:n
        if rfl[i][2][1] == (0,0,0) 
        α[i] = 0
        print("hi")
        else
        α[i] = acos((rfl[i][2][1][1]+rfl[i][2][1][2]+rfl[i][2][1][3])/(sqrt(3)* sqrt((rfl[i][2][1][1]^2+rfl[i][2][1][2]^2+rfl[i][2][1][3]^2)))-0.00000000002)/pi*180
        end
    end
return α
end
#also ich berechne hier einfach nur die winkel zwischen ebenen mit millerindizes. das entspricht den winkeln ihrer normalen also der rez. gittervektoren
# wegen kubischen gitter kann ich einfaches SP benutzen
#
#dannach schaue ich mir die gemessenen reflexe an und kriege damit die richtung von k´(ich sage k, k´haben selben betrag). aus k-k´kann ich die richtung von g berechnen.
#mit diesem g kann ich dann den winkel zu k berechnen, wobei k parallel zu 1 1 1 ist und die reflexe zuordnen. ich kann nur die wiunkel zwischen k und deltak berechnen
#aber ich kann nicht die richtung von deltak im gitterkoordinatensystem bestimmen, darum das winkelgerechne

angles (generic function with 1 method)

In [66]:
using LinearAlgebra

In [104]:
function anglesprax(th, ph)
    th = th .* pi/180
    ph = ph .* pi/180
    kk=[(sin.(th).*cos.(ph))';
     (sin.(th).*sin.(ph))';
      (cos.(th)')]
    println(kk)
    k= [0.0, 0.0, -1.0]
    g = zeros(3,length(th))
    #println(g)
    h= zeros(length(th))
    for i in 1:length(th)
        println(kk[:, i])
        g[:, i] = k .- kk[:, i]
        println(g[:, i])
        g[:, i]=g[:, i]/norm(g[:, i])
        h[i] = acos(k' *g[:, i])/pi*180
    end
    return h
end

anglesprax (generic function with 1 method)

In [106]:
th, ph = [0.0, 90, 60], [0.0, 0, 60]
anglesprax(th, ph)


[0.0 1.0 0.4330127018922194; 0.0 0.0 0.7499999999999999; 1.0 6.123233995736766e-17 0.5000000000000001]
[0.0, 0.0, 1.0]
[0.0, 0.0, -2.0]
[1.0, 0.0, 6.123233995736766e-17]
[-1.0, 0.0, -1.0]
[0.4330127018922194, 0.7499999999999999, 0.5000000000000001]
[-0.4330127018922194, -0.7499999999999999, -1.5]


3-element Vector{Float64}:
  0.0
 45.00000000000001
 29.999999999999993

In [107]:
[1 0 0] - [2 3 4]

1×3 Matrix{Int64}:
 -1  -3  -4